### PR TITLE
Revamped Adapter to Work for SU2 v7.5.0-v7.5.1, Both CHT + FSI

### PR DESCRIPTION
**Pull request by j-signorelli**
Updated adapter now leverages SU2 Python wrapper to successfully complete both CHT and FSI! CDriver.hpp was updated to have added member variables to allow for implicit coupling, and additions/edits were made to python_wrapper_structure.cpp to implement preCICE with ease - these are in the replacement_files directory. The run directory also has two Python scripts to quickly run FSI or CHT cases for usability, but these also can be templates for more specific implementations (for example: it is likely super easy to update these files to handle multiple interfaces).

Images for flow-over-heated-plate and perpendicular-flap are shown below:

flow-over-heated-plate

perpendicular-flap

In regards to the discrepancies in the perpendicular-flap test case above: it is likely because the new adapter uses a new mesh deformation solver that SU2 is transitioning to. The old adapter uses a mesh deformation solver that is now considered "legacy."

And as I had mentioned in the old pull request: I had noticed I was getting different results for perpendicular flap based on the number of processes I was using. Turns out, after a very deep dive: it appears possible it may be a bug on the SU2 side of things, something improper with the config file, or hopefully a quick fix with the FSI template script I provided. Nonetheless: it is not a bug from the added C++ code I implemented, so I decided to go ahead and submit this new PR. The discussion for that is currently ongoing and can be found here: https://github.com/su2code/SU2/discussions/1931. I also included this in the README at the bottom.

The install script automatically pulls previous build options used and provides the (updated if needed) commands to run if needed.

Will be updating the pull request for the tutorials repo shortly!

### CODE REVIEW

**Comment by j-signorelli** [comment]
Just a heads up that the problem stated above is actually an issue just with `MARKER_EULER` in SU2. Clarified this in the README, so it shouldn't be an issue with the non-`EULER` solver. More information can be found at the discussion link.

**Comment by j-signorelli** [comment]
Hi @MakisH ,

I hope you have been doing well! I wanted to give you a heads up: I have maintained a slightly more up-to-date version of this adapter code here: https://github.com/j-signorelli/su2-precice-pywrapper.

I believe that everything after this commit is not presently reflected in this PR: [1778a7ea6f760fbe10151917c9961c2e989f3bf5](https://github.com/j-signorelli/su2-precice-pywrapper/commit/1778a7ea6f760fbe10151917c9961c2e989f3bf5). This includes some bug fixes like saving cycle and time for implicit coupling and additional of capability to handle nondimensionalization. https://github.com/j-signorelli/su2-precice-pywrapper/commits/master/

**Review by MakisH — APPROVED** [review]
Hi there! :wave: You are probably frustrated or at least disappointed by now that this excellent PR had not received a review so far. Sorry for that, it is just that we have no specific maintainer for SU2, I usually have a look over the unmaintained repositories, and I was for several reasons continuously swamped so far. I also only now realized that this is a way cleaner PR than the previous one (thank you!).

I fixed a few small issues, and I will merge and port this to preCICE v3 in a separate PR, to maintain a version working with preCICE v2. The tutorials PR will be merged to directly work with preCICE v3.

We should then also update the [documentation pages on the website](https://precice.org/adapter-su2-overview.html). I will do that and ask for review. Most information could be drawn from this README.

Are you still actively working on anything related to SU2? We could really use some help maintaining this repository. And I think now that this is primarily a Python wrapper, this should be way easier to update to new SU2 versions.

I see that the only invasive changes are now related to checkpointing for implicit coupling. Do you think this is something the SU2 developers could integrate directly in SU2?

**Comment by MakisH** [comment]
> Hi @MakisH ,
> 
> I hope you have been doing well! I wanted to give you a heads up: I have maintained a slightly more up-to-date version of this adapter code here: https://github.com/j-signorelli/su2-precice-pywrapper.
> 
> I believe that everything after this commit is not presently reflected in this PR: [1778a7ea6f760fbe10151917c9961c2e989f3bf5](https://github.com/j-signorelli/su2-precice-pywrapper/commit/1778a7ea6f760fbe10151917c9961c2e989f3bf5). This includes some bug fixes like saving cycle and time for implicit coupling and additional of capability to handle nondimensionalization. https://github.com/j-signorelli/su2-precice-pywrapper/commits/master/

Hi @j-signorelli,

I saw your comment too late, but fortunately I merged without squashing, so merging your next commits should not be complicated. Could you maybe open a follow-up pull request regarding the new changes? I will take care of any merge conflicts.

**Comment by kursatyurt** [comment]
> I see that the only invasive changes are now related to checkpointing for implicit coupling. Do you think this is something the SU2 developers could integrate directly in SU2?

Hi, SU2 has moved to v8, but the Python interface has mostly stayed the same. AFAIK. The adapter can probably be used without much change.

Regarding implicit coupling, no internal checkpoint has been implemented in SU2. Their internal FSI implicit coupling does work without checkpointing. The implicit coupling using preCICE works quite well when no subcycling is required. 

SU2 community is also quite open to the pull request if someone attempts to implement in-memory checkpointing and opens a PR. However, it has to be provided by the community :)

**Comment by MakisH** [comment]
> SU2 community is also quite open to the pull request if someone attempts to implement in-memory checkpointing and opens a PR.

Just to make sure: the implementation of checkpointing in this PR is fully in-memory, right? Or did I miss something?

**Comment by kursatyurt** [comment]
> > SU2 community is also quite open to the pull request if someone attempts to implement in-memory checkpointing and opens a PR.
> 
> Just to make sure: the implementation of checkpointing in this PR is fully in-memory, right? Or did I miss something?

Yes, here it is fully in-memory. 

If someone wants to contribute to the SU2 repository by opening a PR for in-memory checkpointing, SU2 welcomes contributions. This version may be more invasive and probably needs a more careful design, but Pedro can guide :). So, long-term native support with Python wrappers is possible.

**Comment by j-signorelli** [comment]
Hi @MakisH @kursatyurt ,

> Hi there! 👋 You are probably frustrated or at least disappointed by now that this excellent PR had not received a review so far. Sorry for that, it is just that we have no specific maintainer for SU2, I usually have a look over the unmaintained repositories, and I was for several reasons continuously swamped so far. I also only now realized that this is a way cleaner PR than the previous one (thank you!).

Not a problem at all! I also have been endlessly busy.


> Are you still actively working on anything related to SU2? We could really use some help maintaining this repository. And I think now that this is primarily a Python wrapper, this should be way easier to update to new SU2 versions.

I still am actively using SU2, but mostly v7.5.1 and have plans to move on in the (hopefully) near future to more resolved simulations. Nonetheless, I am open to helping with maintaining this repo, but notably there is a LOT of new functionality in the native SU2 v8 Python wrapper that seems to *almost* removes the need for an adapter altogether. For example, these native SU2 functions seem to allow one to get and set the solution at all points of the domain, which is great for implicit coupling:

https://github.com/su2code/SU2/blob/ef8e96812894fb990af9445c7c80b8a3d2e343c9/SU2_CFD/include/drivers/CDriverBase.hpp#L439-L494

I have actually attempted briefly setting up SU2 v8 with preCICE v3 without an adapter, but unfortunately there is no way to adaptively change the timestep natively. I worked on implementing this functionality into SU2, but it turned out to be quite tedious to do in a most general way as the assumption throughout the entirety of SU2 is a constant dt, https://github.com/su2code/SU2/pull/2190.

**Pull request merged**
